### ISSUE TITLE
[Feature] Option to add project when the app boots

### ISSUE THREAD

**Issue by pingvinen** [GabiAxel/google-cloud-gui#3]
I am using this via docker-compose and in it would help the developer experience if it was possible to simply do `docker-compose up` and opening the ui.

Having to manually create the project means that the developer has to do more setup than one would expect.

My suggestion is to add optional arguments to the binary, so it could be used like this:

```
google-cloud-gui --project-id=something-cool --ds-endpoint=hostname:123 --skip-browser
```

**Comment by GabiAxel** [comment]
I think a similar result can be achieved by providing an existing .google-cloud-gui-db.json file and having it copied to the home directory before running google-cloud-gui.

**Comment by pingvinen** [comment]
Cool. That worked :)

It does however expose the "database" schema, so it will make it annoying for users if it changes.

**Comment by GabiAxel** [comment]
Glad the proposed solution works for you.

I think the scope of this project is small and well defined enough to assume that possible future schema changes will not include removing or changing the names, types or meanings of the existing fields, and that new fields will have sensible defaults if missing. Anyway if there are schema changes, they will be documented in a changelog along with migration details if needed.
