### ISSUE TITLE
Executing a page reload on the browser on any state will cause a status 404 response

### ISSUE THREAD

**Issue by brunoais** [GabiAxel/google-cloud-gui#4]
If I follow an URL to any page besides the root page, the server always returns status code 404.

### To reproduce:
1. Navigate your browser to the listening url (E.g. http://localhost:8000)
2. Configure an existing server (press the "+" and fill the form)
3. Enter the project and navigate anywhere.
4. Keyboard: press F5 (or any reload order)

###Problem
Page reloads into empty page (browser tools show it is returning a status code 404)
###Expected results:
(after loading) Page appears the same as it was before step 4 was executed.
### Major use-case
Duplicate page to compare data (example, compare data between two entities and not having to re-execute the steps to arrive to the data next to the one being checked.

**Comment by brunoais** [comment]
great, thank you.

**Comment by GabiAxel** [comment]
Thanks for catching this. I just published 0.2.1 with the fix.
