### ISSUE TITLE
If an entry has long data, the dialog appears annoyingly narrow

### ISSUE THREAD

**Issue by brunoais** [GabiAxel/google-cloud-gui#5]
![baddialogsize](https://user-images.githubusercontent.com/639467/39917173-9b8d109c-5504-11e8-993d-e37f8e78ff53.png)
I have a lot of screen leftover that could have been used to show more data but, instead, I have to scroll to get to it. After some uses, it quickly becomes annoying.
Due to the auto-generative (look-like) of the CSS, doing an userscript to override this is also not practical.

I do wonder if this problem also shows vertically.... Unfortunately, though, I don't have test data for such.

**Comment by GabiAxel** [comment]
Thanks for the report. Before I publish a new version with the fix, I would appreciate if you could test it and let me know if this looks good for your data.

**Comment by brunoais** [comment]
How do I test the new version?

**Comment by brunoais** [comment]
@GabiAxel I just can't find the time while I'm at work to deal with this as I'm not currently actively working with the emulator for now. Sorry for the lack of input.

**Comment by GabiAxel** [comment]
That's fine. I released 0.2.2 with this change and also added a screenshot of the new dialog (and other screens), so you can get an impression of it.
